# Generated by Django 5.0.6 on 2024-05-29 02:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_whishlist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Wishlist",
        ),
    ]
