# Generated by Django 5.0.2 on 2024-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_status",
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid",
            field=models.BooleanField(default=True),
        ),
    ]
